name: Scrape Football Table

on:
  schedule:
    # This runs the code at the top of every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    # This allows you to run it manually

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run scraper
        # 'env' and 'run' must have the same indentation
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          THESPORTSDB_API_KEY: ${{ secrets.THESPORTSDB_API_KEY }}
        run: python scrape_and_post.py
